### PR TITLE
Add missing and improve German translations

### PR DESCRIPTION
**Pull request by pr0gr8mm3r**

### CODE REVIEW

**Comment by danestves** [comment]
Hi @pr0gr8mm3r thanks for the change! Can you make a new version of the `package.json` and also put a correct syntax for `CHANGELOG.md`?

**Comment by pr0gr8mm3r** [comment]
☑ Done
However, I don't quite get the versioning system, so I just chose `0.2.75`. Feel free to make changes to my branch, edits by maintainers is enabled.

**Comment by pr0gr8mm3r** [comment]
Hey, would you mind publishing the new version? ;)

**Comment by danestves** [comment]
Sorry for the delay @pr0gr8mm3r ! Here is the new version https://www.npmjs.com/package/strapi-plugin-preview-content

**Comment by pr0gr8mm3r** [comment]
Thank you!

**Pull request merged**
