### PR TITLE
Add Contribution guide

### LINKED ISSUE #12: Create documentation on how to contribute
The repository structure makes it rather hard to test changes in a local test environment. I tried cloning this repository into an existing strapi application's plugins folder, but because the files are all in the src folder instead of root, it doesn't build. I couldn't figure out a way to set it up correctly.

I believe it would be beneficial to the project if there were guidance on how to set this up.

### PR DESCRIPTION
**Pull request by pr0gr8mm3r**
Fixes #12.

### CODE REVIEW

**Comment by danestves** [comment]
Thank you @pr0gr8mm3r i really didn't have the time to work on this

**Comment by pr0gr8mm3r** [comment]
No worries @danestves!
I'm in the process of setting up my own environment, so I thought I might as well write it down.

**Comment by danestves** [comment]
Tell me when it's done and i'll merge it

**Comment by pr0gr8mm3r** [comment]
It's done now :+1:

**Pull request merged**
